### ISSUE TITLE
sin^2 x

### ISSUE THREAD

**Issue by davidfarmer** [davidfarmer/SpaceMath#15]
Has space after `sin`.

Need to handle this as a special case for trig-like functions.

**Comment by Alex-Jordan** [comment]
Maybe your note here captures this, but I meant more than one thing when I reported what I saw. (Although, maybe they all come from the same root issue.) With `$sin^2 x$`:
* There is visual space between the `sin` and the `²`.
* The speech comes out as `sine quantity endquantity squared times x` instead of `sine squared of x`. The "times" is particularly noteworthy, and is maybe unrelated to the space, since these two things are on opposite sides of the `²`/`squared`.
* The MathML looks like it would not semantically capture "sine squared of x", and yet if I plug that MathML into MathJax, I get `sine squared x` which is not bad. But I can't tell if MathJax understand the right meaning, or is just giving speech for the little bits that it can give speech to, and it happens to work out.
